### ISSUE TITLE
why I can not see the burndown chart？

### ISSUE THREAD

**Issue by archonwang** [savoirfairelinux/redmine-timebank#2]
Hi, @support-savoirfairelinux 
could you please tell me why I can not see the burndown chart? It's strange. 

I used advanced_roadmap_V2( https://github.com/Coren/redmine_advanced_roadmap_v2 ) also .Is is compatabile each other? Thanks.

**Comment by ghost** [comment]
Do you have the Redmine Backlogs plugin installed ?
https://github.com/backlogs/redmine_backlogs/tree/feature/redmine3

I would be surprised that TimeBank is compatible with Advanced Roadmap, a big part of the Roadmap page is overriden. If you try, it would be interesting to have your feedback about it.

Have a great day !

**Comment by archonwang** [comment]
@dcotet, Thanks for your reply, 
I never installed redmine_backlogs. I tested it on my environment and it worked well except the burndown chart.

**Comment by ghost** [comment]
The burndown chart is a block called from Redmine Backlogs plugin. You will need to get it installed to make the burndown chart appears.

Have a great day !

**Comment by archonwang** [comment]
oo, I got it ,thanks. @dcotet
